In [3]:
import numpy as np
import pandas as pd

In [4]:
test = pd.read_csv(r"C:\Users\shree\OneDrive\Documents\ipl.csv")
test.head(10)
test.shape
test.describe()
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76014 entries, 0 to 76013
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   mid             76014 non-null  int64  
 1   date            76014 non-null  object 
 2   venue           76014 non-null  object 
 3   bat_team        76014 non-null  object 
 4   bowl_team       76014 non-null  object 
 5   batsman         76014 non-null  object 
 6   bowler          76014 non-null  object 
 7   runs            76014 non-null  int64  
 8   wickets         76014 non-null  int64  
 9   overs           76014 non-null  float64
 10  runs_last_5     76014 non-null  int64  
 11  wickets_last_5  76014 non-null  int64  
 12  striker         76014 non-null  int64  
 13  non-striker     76014 non-null  int64  
 14  total           76014 non-null  int64  
dtypes: float64(1), int64(8), object(6)
memory usage: 8.7+ MB


In [5]:
print(test['mid'].unique())

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [6]:
remove_list = ['mid','venue','batsman','bowler','striker','non-striker']
print("Before removing unwanted columns {}".format(test.shape))
test.drop(remove_list,axis = 1,inplace = True)
print("After removing unwanted columns {}".format(test.shape))
test

Before removing unwanted columns (76014, 15)
After removing unwanted columns (76014, 9)


date               bat_team                    bowl_team  runs  \
0      2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     1   
1      2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     1   
2      2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     2   
3      2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     2   
4      2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     2   
...           ...                    ...                          ...   ...   
76009  2017-05-21         Mumbai Indians       Rising Pune Supergiant   121   
76010  2017-05-21         Mumbai Indians       Rising Pune Supergiant   127   
76011  2017-05-21         Mumbai Indians       Rising Pune Supergiant   128   
76012  2017-05-21         Mumbai Indians       Rising Pune Supergiant   129   
76013  2017-05-21         Mumbai Indians       Rising Pune Supergiant   129   

       wickets  overs  runs_last_5  wickets_last_5  total  
0            0    0.1            1               0    222  
1            0    0.2            1               0    222  
2            0    0.2            2               0    222  
3            0    0.3            2               0    222  
4            0    0.4            2               0    222  
...        ...    ...          ...             ...    ...  
76009        7   19.2           40               0    129  
76010        7   19.3           46               0    129  
76011        7   19.4           47               0    129  
76012        7   19.5           48               0    129  
76013        8   19.6           47               1    129  

[76014 rows x 9 columns]

In [7]:
test['bat_team'].unique()
test['bowl_team'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Mumbai Indians', 'Chennai Super Kings', 'Deccan Chargers',
       'Pune Warriors', 'Kochi Tuskers Kerala', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant'], dtype=object)

In [8]:
consistent_teams = ['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Mumbai Indians', 'Chennai Super Kings',
       'Sunrisers Hyderabad']

In [9]:
df = test[(test['bat_team'].isin(consistent_teams)) & (test['bowl_team'].isin(consistent_teams))]
print(df)

             date               bat_team                    bowl_team  runs  \
0      2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     1   
1      2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     1   
2      2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     2   
3      2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     2   
4      2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     2   
...           ...                    ...                          ...   ...   
75884  2017-05-19  Kolkata Knight Riders               Mumbai Indians   106   
75885  2017-05-19  Kolkata Knight Riders               Mumbai Indians   107   
75886  2017-05-19  Kolkata Knight Riders               Mumbai Indians   107   
75887  2017-05-19  Kolkata Knight Riders               Mumbai Indians   107   
75888  2017-05-19  Kolkata Knight Riders               Mumbai Indians   107   

       wickets  overs  runs_last_5  wickets_last_5 

In [10]:
df = df[df['overs']>=5]
df

date               bat_team                    bowl_team  runs  \
32     2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
33     2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
34     2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
35     2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
36     2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
...           ...                    ...                          ...   ...   
75884  2017-05-19  Kolkata Knight Riders               Mumbai Indians   106   
75885  2017-05-19  Kolkata Knight Riders               Mumbai Indians   107   
75886  2017-05-19  Kolkata Knight Riders               Mumbai Indians   107   
75887  2017-05-19  Kolkata Knight Riders               Mumbai Indians   107   
75888  2017-05-19  Kolkata Knight Riders               Mumbai Indians   107   

       wickets  overs  runs_last_5  wickets_last_5  total  
32           0    5.1           59               0    222  
33           1    5.2           59               1    222  
34           1    5.3           59               1    222  
35           1    5.4           59               1    222  
36           1    5.5           58               1    222  
...        ...    ...          ...             ...    ...  
75884        9   18.1           29               4    107  
75885        9   18.2           29               4    107  
75886        9   18.3           28               4    107  
75887        9   18.4           24               4    107  
75888       10   18.5           23               5    107  

[40108 rows x 9 columns]

In [11]:
# from matplotlib import pyplot as plt
# import seaborn as sns
# def _plot_series(series, series_name, series_index=0):
#   from matplotlib import pyplot as plt
#   import seaborn as sns
#   palette = list(sns.palettes.mpl_palette('Dark2'))
#   xs = series['index']
#   ys = series['runs']

#   plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

# fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
# df_sorted = _df_10.sort_values('index', ascending=True)
# for i, (series_name, series) in enumerate(df_sorted.groupby('bat_team')):
#   _plot_series(series, series_name, i)
#   fig.legend(title='bat_team', bbox_to_anchor=(1, 1), loc='upper left')
# sns.despine(fig=fig, ax=ax)
# plt.xlabel('index')
# _ = plt.ylabel('runs')

In [12]:
from datetime import datetime
import pandas as pd
x = df['date']
df['date'] = df['date'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d'))
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 40108 entries, 32 to 75888
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   date            40108 non-null  datetime64[ns]
 1   bat_team        40108 non-null  object        
 2   bowl_team       40108 non-null  object        
 3   runs            40108 non-null  int64         
 4   wickets         40108 non-null  int64         
 5   overs           40108 non-null  float64       
 6   runs_last_5     40108 non-null  int64         
 7   wickets_last_5  40108 non-null  int64         
 8   total           40108 non-null  int64         
dtypes: datetime64[ns](1), float64(1), int64(5), object(2)
memory usage: 3.1+ MB


In [13]:
import pandas as pd
encoded_df = pd.get_dummies(data = df, columns =['bat_team','bowl_team'])
encoded_df

date  runs  wickets  overs  runs_last_5  wickets_last_5  total  \
32    2008-04-18    61        0    5.1           59               0    222   
33    2008-04-18    61        1    5.2           59               1    222   
34    2008-04-18    61        1    5.3           59               1    222   
35    2008-04-18    61        1    5.4           59               1    222   
36    2008-04-18    61        1    5.5           58               1    222   
...          ...   ...      ...    ...          ...             ...    ...   
75884 2017-05-19   106        9   18.1           29               4    107   
75885 2017-05-19   107        9   18.2           29               4    107   
75886 2017-05-19   107        9   18.3           28               4    107   
75887 2017-05-19   107        9   18.4           24               4    107   
75888 2017-05-19   107       10   18.5           23               5    107   

       bat_team_Chennai Super Kings  bat_team_Delhi Daredevils  \
32                                0                          0   
33                                0                          0   
34                                0                          0   
35                                0                          0   
36                                0                          0   
...                             ...                        ...   
75884                             0                          0   
75885                             0                          0   
75886                             0                          0   
75887                             0                          0   
75888                             0                          0   

       bat_team_Kings XI Punjab  ...  bat_team_Royal Challengers Bangalore  \
32                            0  ...                                     0   
33                            0  ...                                     0   
34                            0  ...                                     0   
35                            0  ...                                     0   
36                            0  ...                                     0   
...                         ...  ...                                   ...   
75884                         0  ...                                     0   
75885                         0  ...                                     0   
75886                         0  ...                                     0   
75887                         0  ...                                     0   
75888                         0  ...                                     0   

       bat_team_Sunrisers Hyderabad  bowl_team_Chennai Super Kings  \
32                                0                              0   
33                                0                              0   
34                                0                              0   
35                                0                              0   
36                                0                              0   
...                             ...                            ...   
75884                             0                              0   
75885                             0                              0   
75886                             0                              0   
75887                             0                              0   
75888                             0                              0   

       bowl_team_Delhi Daredevils  bowl_team_Kings XI Punjab  \
32                              0                          0   
33                              0                          0   
34                              0                          0   
35                              0                          0   
36                              0                          0   
...                           ...                        ...   
75884                           0                       

In [14]:



encoded_df.columns

Index(['date', 'runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5',
       'total', 'bat_team_Chennai Super Kings', 'bat_team_Delhi Daredevils',
       'bat_team_Kings XI Punjab', 'bat_team_Kolkata Knight Riders',
       'bat_team_Mumbai Indians', 'bat_team_Rajasthan Royals',
       'bat_team_Royal Challengers Bangalore', 'bat_team_Sunrisers Hyderabad',
       'bowl_team_Chennai Super Kings', 'bowl_team_Delhi Daredevils',
       'bowl_team_Kings XI Punjab', 'bowl_team_Kolkata Knight Riders',
       'bowl_team_Mumbai Indians', 'bowl_team_Rajasthan Royals',
       'bowl_team_Royal Challengers Bangalore',
       'bowl_team_Sunrisers Hyderabad'],
      dtype='object')

In [15]:
encoded_df = encoded_df[['date', 'bat_team_Chennai Super Kings', 'bat_team_Delhi Daredevils',
       'bat_team_Kings XI Punjab', 'bat_team_Kolkata Knight Riders',
       'bat_team_Mumbai Indians', 'bat_team_Rajasthan Royals',
       'bat_team_Royal Challengers Bangalore', 'bat_team_Sunrisers Hyderabad',
       'bowl_team_Chennai Super Kings', 'bowl_team_Delhi Daredevils',
       'bowl_team_Kings XI Punjab', 'bowl_team_Kolkata Knight Riders',
       'bowl_team_Mumbai Indians', 'bowl_team_Rajasthan Royals',
       'bowl_team_Royal Challengers Bangalore',
       'bowl_team_Sunrisers Hyderabad','overs', 'runs', 'wickets', 'runs_last_5', 'wickets_last_5',
       'total']]
encoded_df


date  bat_team_Chennai Super Kings  bat_team_Delhi Daredevils  \
32    2008-04-18                             0                          0   
33    2008-04-18                             0                          0   
34    2008-04-18                             0                          0   
35    2008-04-18                             0                          0   
36    2008-04-18                             0                          0   
...          ...                           ...                        ...   
75884 2017-05-19                             0                          0   
75885 2017-05-19                             0                          0   
75886 2017-05-19                             0                          0   
75887 2017-05-19                             0                          0   
75888 2017-05-19                             0                          0   

       bat_team_Kings XI Punjab  bat_team_Kolkata Knight Riders  \
32                            0                               1   
33                            0                               1   
34                            0                               1   
35                            0                               1   
36                            0                               1   
...                         ...                             ...   
75884                         0                               1   
75885                         0                               1   
75886                         0                               1   
75887                         0                               1   
75888                         0                               1   

       bat_team_Mumbai Indians  bat_team_Rajasthan Royals  \
32                           0                          0   
33                           0                          0   
34                           0                          0   
35                           0                          0   
36                           0                          0   
...                        ...                        ...   
75884                        0                          0   
75885                        0                          0   
75886                        0                          0   
75887                        0                          0   
75888                        0                          0   

       bat_team_Royal Challengers Bangalore  bat_team_Sunrisers Hyderabad  \
32                                        0                             0   
33                                        0                             0   
34                                        0                             0   
35                                        0                             0   
36                                        0                             0   
...                                     ...                           ...   
75884                                     0                             0   
75885                                     0                             0   
75886                                     0                             0   
75887                                     0                             0   
75888                                     0                             0   

       bowl_team_Chennai Super Kings  ...  bowl_team_Mumbai Indians  \
32                                 0  ...                         0   
33                                 0  ...                         0   
34                                 0  ...                         0   
35                                 0  ...                         0   
36                                 0  ...                         0   
...                              ...  ...                       ...   
75884                              0  ...                         1   
75885                              0  ...               

In [16]:
import pandas as pd
x_train = encoded_df.drop(labels = 'total',axis = 1 )[encoded_df['date'].dt.year <= 2016]
x_test = encoded_df.drop(labels = 'total',axis = 1 )[encoded_df['date'].dt.year >= 2017]

y_train = encoded_df[encoded_df['date'].dt.year <= 2016]['total'].values
y_test = encoded_df[encoded_df['date'].dt.year >= 2017]['total'].values

x_train.drop(labels = 'date',axis = True , inplace = True)
x_test.drop(labels = 'date',axis = True , inplace = True)

print(x_test)
print(x_train)
np.shape(y_train)

       bat_team_Chennai Super Kings  bat_team_Delhi Daredevils  \
68894                             0                          0   
68895                             0                          0   
68896                             0                          0   
68897                             0                          0   
68898                             0                          0   
...                             ...                        ...   
75884                             0                          0   
75885                             0                          0   
75886                             0                          0   
75887                             0                          0   
75888                             0                          0   

       bat_team_Kings XI Punjab  bat_team_Kolkata Knight Riders  \
68894                         0                               0   
68895                         0                               0   
68896 

(37330,)

In [17]:
!pip  install scikit-learn
from sklearn.linear_model import LinearRegression

Defaulting to user installation because normal site-packages is not writeable


In [18]:
linear_regressor = LinearRegression()
linear_regressor.fit(x_train,y_train)

LinearRegression()

In [19]:
y_pred_lr = linear_regressor.predict(x_test)
y_pred_lr


array([171.98266602, 175.13085938, 174.52856445, ..., 100.31054688,
        99.74316406,  93.08081055])

In [20]:
from sklearn.metrics import mean_absolute_error as mae , mean_squared_error as mse


In [21]:
print("----------Linear Reggression- Model Evaluvation-----------")
print("Mean Absolute Error (MAE) : {}".format(mae(y_test,y_pred_lr)))
print("Mean Squared Error (MSE) : {}".format(mse(y_test,y_pred_lr)))
print("Root MeanSquared Error (RMSE) : {}".format(np.sqrt(mse(y_test,y_pred_lr))))

----------Linear Reggression- Model Evaluvation-----------
Mean Absolute Error (MAE) : 12.123852503909061
Mean Squared Error (MSE) : 251.3118638646654
Root MeanSquared Error (RMSE) : 15.852818798707863


In [22]:
print(linear_regressor.score(x_test,y_test))
print(linear_regressor.score(x_train,y_train))

0.751963377005507
0.6502067075044439


In [23]:
from sklearn.tree import DecisionTreeRegressor
Decision_Regressor = DecisionTreeRegressor()
Decision_Regressor.fit(x_train,y_train)

DecisionTreeRegressor()

In [24]:
y_pred_dr = Decision_Regressor.predict(x_test)
y_pred_dr


array([194., 194., 194., ..., 119., 113., 113.])

In [25]:
print(Decision_Regressor.score(x_test,y_test))
print(Decision_Regressor.score(x_train,y_train))

0.46456697475552666
0.9998567447518953


In [26]:
print("----------Linear Reggression- Model Evaluvation-----------")
print("Mean Absolute Error (MAE) : {}".format(mae(y_test,y_pred_dr)))
print("Mean Squared Error (MSE) : {}".format(mse(y_test,y_pred_dr)))
print("Root MeanSquared Error (RMSE) : {}".format(np.sqrt(mse(y_test,y_pred_dr))))

----------Linear Reggression- Model Evaluvation-----------
Mean Absolute Error (MAE) : 17.114470842332615
Mean Squared Error (MSE) : 542.5032397408207
Root MeanSquared Error (RMSE) : 23.291698944920714


In [27]:
from sklearn.ensemble import RandomForestRegressor
Random_Regressor = RandomForestRegressor()
Random_Regressor.fit(x_train,y_train)

RandomForestRegressor()

In [28]:
y_pred_rr = Decision_Regressor.predict(x_test)
y_pred_rr


array([194., 194., 194., ..., 119., 113., 113.])

In [29]:
print(Random_Regressor.score(x_test,y_test))
print(Random_Regressor.score(x_train,y_train))

0.66576914989609
0.9923333453643176


In [30]:
print("----------Linear Reggression- Model Evaluvation-----------")
print("Mean Absolute Error (MAE) : {}".format(mae(y_test,y_pred_rr)))
print("Mean Squared Error (MSE) : {}".format(mse(y_test,y_pred_rr)))
print("Root MeanSquared Error (RMSE) : {}".format(np.sqrt(mse(y_test,y_pred_rr))))

----------Linear Reggression- Model Evaluvation-----------
Mean Absolute Error (MAE) : 17.114470842332615
Mean Squared Error (MSE) : 542.5032397408207
Root MeanSquared Error (RMSE) : 23.291698944920714


In [31]:
from sklearn.ensemble import AdaBoostRegressor

Ada_Regressor =AdaBoostRegressor(base_estimator=linear_regressor, n_estimators=100, learning_rate=25)

Ada_Regressor.fit(x_train,y_train)

C:\Users\shree\AppData\Roaming\Python\Python311\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


AdaBoostRegressor(base_estimator=LinearRegression(), learning_rate=25,
                  n_estimators=100)

In [32]:
y_pred_ad = Ada_Regressor.predict(x_test)
y_pred_ad


array([68.5, 68.5, 68.5, ..., 67. , 67. , 67. ])

In [33]:
print(Ada_Regressor.score(x_test,y_test))
print(Ada_Regressor.score(x_train,y_train))

-9.619837100518765
-9.858045507651227


In [34]:
print("----------Linear Reggression- Model Evaluvation-----------")
print("Mean Absolute Error (MAE) : {}".format(mae(y_test,y_pred_ad)))
print("Mean Squared Error (MSE) : {}".format(mse(y_test,y_pred_ad)))
print("Root MeanSquared Error (RMSE) : {}".format(np.sqrt(mse(y_test,y_pred_ad))))

----------Linear Reggression- Model Evaluvation-----------
Mean Absolute Error (MAE) : 98.8040856731461
Mean Squared Error (MSE) : 10760.068507019425
Root MeanSquared Error (RMSE) : 103.73075005522435


In [35]:
def predict_score(batting_team = "Chennai Super Kings", bowling_team = "Mumbai Indians",overs =5.1, runs =50  , wickets = 0, runs_last_5 = 0, wickets_last_5 = 0):
  temp_array = list()
  if batting_team == 'Chennai Super Kings':
    temp_array = temp_array + [1,0,0,0,0,0,0,0]
  elif batting_team == 'Delhi Daredevils':
    temp_array = temp_array + [0,1,0,0,0,0,0,0]
  elif batting_team == 'Kings XI Punjab':
    temp_array = temp_array + [0,0,1,0,0,0,0,0]
  elif batting_team == 'Kolkata Knight Riders':
    temp_array = temp_array + [0,0,0,1,0,0,0,0]
  elif batting_team == 'Mumbai Indians':
    temp_array = temp_array + [0,0,0,0,1,0,0,0]
  elif batting_team == 'Rajasthan Royals':
    temp_array = temp_array + [0,0,0,0,0,1,0,0]
  elif batting_team == 'Royal Challengers Bangalore':
    temp_array = temp_array + [0,0,0,0,0,0,1,0]
  elif batting_team == 'Sunrisers Hyderabad':
    temp_array = temp_array + [0,0,0,0,0,0,0,1]

  if bowling_team == 'Chennai Super Kings':
    temp_array = temp_array + [1,0,0,0,0,0,0,0]
  elif bowling_team == 'Delhi Daredevils':
    temp_array = temp_array + [0,1,0,0,0,0,0,0]
  elif bowling_team == 'Kings XI Punjab':
    temp_array = temp_array + [0,0,1,0,0,0,0,0]
  elif bowling_team == 'Kolkata Knight Riders':
    temp_array = temp_array + [0,0,0,1,0,0,0,0]
  elif bowling_team == 'Mumbai Indians':
    temp_array = temp_array + [0,0,0,0,1,0,0,0]
  elif bowling_team == 'Rajasthan Royals':
    temp_array = temp_array + [0,0,0,0,0,1,0,0]
  elif bowling_team == 'Royal Challengers Bangalore':
    temp_array = temp_array + [0,0,0,0,0,0,1,0]
  elif bowling_team == 'Sunrisers Hyderabad':
    temp_array = temp_array + [0,0,0,0,0,0,0,1]

  temp_array = temp_array +[overs, runs , wickets, runs_last_5, wickets_last_5]

  temp_array = np.array([temp_array])
  print(temp_array)

  return int(linear_regressor.predict(temp_array))

In [41]:
final_score = predict_score( batting_team = 'Kolkata Knight Riders', bowling_team = 'Delhi Daredevils',overs = 7, runs = 2, wickets = 2, runs_last_5 = 23, wickets_last_5 = 2 )
print("The final predicted score (range): {}".format(final_score - 10, final_score + 10))

[[ 0  0  0  1  0  0  0  0  0  1  0  0  0  0  0  0  7  2  2 23  2]]
The final predicted score (range): 98


C:\Users\shree\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\shree\AppData\Local\Temp\ipykernel_4652\2965757292.py:42: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(linear_regressor.predict(temp_array))


In [42]:
final_score = predict_score( batting_team = 'Mumbai Indians', bowling_team = 'Chennai Super Kings',overs = 17, runs = 22, wickets = 2, runs_last_5 = 23, wickets_last_5 = 0 )
print("The final predicted score (range): {}".format(final_score - 10, final_score + 10))

[[ 0  0  0  0  1  0  0  0  1  0  0  0  0  0  0  0 17 22  2 23  0]]
The final predicted score (range): 61


C:\Users\shree\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\shree\AppData\Local\Temp\ipykernel_4652\2965757292.py:42: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(linear_regressor.predict(temp_array))


In [46]:
#model into front end module
import pickle
with open("iplmodule","wb") as f:
     pickle.dump(linear_regressor,f)